articles/urls.py
from django.urls import path

from .views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, RecipeListView, \
    RecipeDetailView

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view(), name='articles_list'),
    path('create-new-article/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('article/<slug:slug>/edit/', ArticleUpdateView.as_view(), name='article_update'),
    path('recipes/', RecipeListView.as_view(), name='recipes_list'),
    path('recipes/<slug:slug>/', RecipeDetailView.as_view(), name='recipe_detail'),
]

pages/urls.py
from django.urls import path

from .views import homepage_view, TapTheTableSignupView, AboutView, MeetEditorView, ContactUsView, \
    pizzavegan_signup_view

app_name = 'pages'
urlpatterns = [
    path('', homepage_view, name='home'),
    path('register/', TapTheTableSignupView.as_view(), name='tap-the-table'),
    path('about/', AboutView.as_view(), name='about'),
    path('meet-the-editor/', MeetEditorView.as_view(), name='meet-the-editor'),
    path('contact/', ContactUsView.as_view(), name='contact_us'),
    path('pizzavegan-signup/', pizzavegan_signup_view, name='pizzavegan-signup'),
]

pizzavegan_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('articles/', include('articles.urls')),
    path('pizzerias/', include('pizzerias.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/models.py
from django.db import models

from .helpers import geocode_address


class TapTheTableResponse(models.Model):
    restaurant_name = models.CharField(max_length=200)
    email_address = models.EmailField(max_length=200)
    street_address1 = models.CharField(max_length=100, blank=True, verbose_name='Street Address 1')
    street_address2 = models.CharField(max_length=100, blank=True, verbose_name='Street Address 2')
    city = models.CharField(max_length=50, blank=True)
    state = models.CharField(max_length=30, blank=True)
    zip_code = models.CharField(max_length=15, blank=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, default=0)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, default=0)
    vegan_pizza_type = models.CharField(max_length=200)
    menu_description = models.TextField(blank=True)
    facebook_page = models.CharField(max_length=200, blank=True)
    online_ordering_link = models.CharField(max_length=200, blank=True)
    pizza_photo = models.ImageField(upload_to='images/', blank=True)
    is_subscriber = models.BooleanField(verbose_name='Subscribes to PMQ?',
                                        help_text='Indicates whether this pizzeria subscribes to PMQ Magazine',
                                        default=False)
    is_approved = models.BooleanField(help_text='Indicates whether this listing has been approved for display',
                                      default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.restaurant_name

    def save(self, *args, **kwargs):
        try:
            lat_lng = geocode_address(self.street_address1, self.city, self.state)
            self.latitude = lat_lng['lat']
            self.longitude = lat_lng['lng']
        except Exception as e:
            print(f'Geocoding failed for {self.restaurant_name}')
        super(TapTheTableResponse, self).save(*args, **kwargs)


class SurveyResponse(models.Model):
    email = models.EmailField(max_length=200)
    pizza_description = models.TextField(blank=True)

    def __str__(self):
        return self.email


class ContactUsResponse(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.email

contacts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import TapTheTableResponse, SurveyResponse, ContactUsResponse


class TapTheTableForm(forms.ModelForm):

    class Meta:
        model = TapTheTableResponse
        fields = ('restaurant_name', 'email_address', 'vegan_pizza_type', 'menu_description', 'facebook_page',
                  'online_ordering_link', 'pizza_photo', 'is_subscriber')
        labels = {
            'restaurant_name': _('What is the name of your restaurant?'),
            'email_address': _('What is your email address?'),
            'vegan_pizza_type': _('Which vegan pizza would you like to feature in this promotion?'),
            'menu_description': _('Please provide a description of your pizza.'),
            'facebook_page': _('What is the link to your pizzeria\'s Facebook page?'),
            'online_ordering_link': _('What is your online ordering link?'),
            'pizza_photo': _('Please upload a photo of the pizza you would like to feature.'),
            'is_subscriber': _('Are you a PMQ subscriber?'),
        }
        help_texts = {
            'is_subscriber': _('Please check if you are a current subscriber to PMQ Pizza Magazine.'),
            'pizza_photo': _('Maximum file size: 5MB'),
        }


class SurveyResponseForm(forms.ModelForm):

    class Meta:
        model = SurveyResponse
        fields = ('email', 'pizza_description', )
        labels = {
            'email': _('If you\'d like to get a notification for our launch party, drop your email below:'),
            'pizza_description': _('Also, if there is a vegan pizza you\'d like to recommend or boast about, '
                                   'feel free to share it with us! Maybe it\'ll get featured in a future promotion!'),
        }
        widgets = {
            'pizza_description': forms.Textarea(attrs={'rows': 3})
        }


class ContactUsForm(forms.ModelForm):

    class Meta:
        model = ContactUsResponse
        fields = ('name', 'email', 'message', )
        labels = {
            'name': _('Your name'),
            'email': _('Your email'),
            'message': _('What is your message?'),
        }
        widgets = {
            'message': forms.Textarea(attrs={'rows': 5})
        }

contacts/views.py
from django.shortcuts import render

# Create your views here.

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | About{% endblock title %}

{% block content %}
    <main class="container-fluid my-5 px-5">
        <div class="row justify-content-center">
            <div class="col-10 col-md-7 col-lg-5">
                <h2 class="responsive-header primary-text">About PizzaVegan.com</h2>
                <hr>
                <p>
                    PizzaVegan.com is designed to connect the ever-growing vegan consumer community with pizzerias that
                    are offering vegan-friendly menu items&mdash;and to encourage consumers and pizzeria owners alike
                    to expand their vegan knowledge via recipes, profiles, products, informative articles and more.
                </p>
                <p>
                    Vegan diets have gained incredible traction in recent years, and experts say this movement is no
                    mere fad or trend. It reflects a true shift in eating habits that will continue to grow in the
                    future. For example, according to a 2020 poll of 2,000 adults by OnePoll, 39% of people ages 18 to
                    25, and 23% of people ages 26 to 41, already exclude animal products from their diets. Other studies
                    show that even meat eaters are adding in more plant-based meals and embracing the flexitarian
                    lifestyle.
                </p>
                <p>
                    Whether their goals are planetary sustainability, improved health or protecting the animal
                    population, more consumers are seeking vegan options in restaurants around the country and
                    world&mdash;including, of course, within Americans’ favorite food category: pizza.
                </p>
                <p>
                    Explore PizzaVegan.com and reap the benefits. Learn more about vegan diets, discover new vegan
                    products and vegan pizza recipes, and check out the trailblazers who are changing the face of
                    veganism from niche to mainstream.
                </p>
                <p>
                    If you’re a pizzeria owner, register your pizzeria with us to highlight your vegan-friendly menu
                    items. If you’re a consumer, refer to our directory to find vegan-friendly pizzerias in your area.
                    We welcome you all to the world’s largest vegan pizza community on the web!
                </p>
                <p>
                    Do you want to be featured on PizzaVegan.com? Have a suggestion or question for our editor? Reach
                    out to us at tracy@pizzavegan.com.
                </p>
            </div>
        </div>
    </main>
{% endblock content %}

templates/pages/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} | Contact Us{% endblock title %}

{% block content %}
    <div class="container-fluid my-5">
        <div class="row justify-content-center">
            <div class="col-12 col-md-10 col-lg-7 col-xl-5">
                {% include 'partials/_alerts.html' %}
                <h2 class="responsive-header primary-text">Contact Us</h2>
                <p class="lead">
                    Do you have a message for the PizzaVegan.com staff? Fill out the form below!
                </p>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-outline-success btn-block mt-4">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-10">
            <h2 class="responsive-header primary-text">Pizza Vegan Community</h2>
            <p class="lead responsive-lead">Vegan pizza at your fingertips&mdash;literally!</p>
        </div>
    </div>
</div>

    <div class="container my-4">
        <div class="row">
            {% for article in articles_list %}
                <article class="col-12 col-md-6 col-lg-4 d-flex flex-column mt-3 mb-5">
                    <img src="{{ article.featured_image.url }}" alt="{{ article.title }}" class="articles-list-image rounded" />
                    <h4 class="articles-list-post-title mt-3">
                        <a href="{% url 'articles:article_detail' article.slug %}" class="text-success">
                            {{ article.title }}
                        </a>
                    </h4>
                    <p class="articles-list-post-meta mt-1">Posted on {{ article.created_on|date:'F j, Y' }}</p>
                    <p>{{ article.subtitle }}</p>
                    <a href="{% url 'articles:article_detail' article.slug %}" class="btn btn-outline-success btn-block mt-auto">
                        Read More
                    </a>
                </article>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

templates/pages/meet-the-editor.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | Meet the Editor{% endblock title %}

{% block content %}
    <main class="container-fluid my-5 px-5">
        <div class="row justify-content-center">
            <div class="col-10 col-md-7 col-lg-5">
                <h2 class="responsive-header primary-text mt-4">Meet the Editor</h2>
                <hr>
                <div class="article-header-image mb-4 shadow">
                    <img src="{% static 'images/tracy.jpg' %}" class="rounded" />
                </div>
                <p>
                    Tracy Morin joined PMQ Pizza Magazine as senior copy editor in 2008 and has since traveled the
                    world to meet with some of the industry's most dedicated and accomplished pizzeria owners, chefs
                    and employees. As a longtime magazine writer and editor, Morin is a regular contributor of PMQ
                    feature articles on food and beverage, equipment, marketing and more. She also writes the monthly
                    column <a href="http://pizzahalloffame.com/" class="text-success" target="_blank">Pizza Hall of
                    Fame</a>, which profiles historic pizzerias and received the National Award of Excellence from the
                    American Society of Business Publication Editors in 2011.
                </p>
                <p>
                    In addition to her passion for pizza, Morin brings a firsthand understanding of alternative diets
                    to the PizzaVegan.com community. A vegetarian since 1995, she has welcomed the booming growth of
                    cruelty-free foods in recent years&mdash;and the ever-growing number of consumers who crave them.
                    In her position as editor of PizzaVegan.com, she relishes the opportunity to oversee a thriving
                    community of vegan pizza lovers and the enterprising pizzeria owners who are successfully catering
                    to this burgeoning market.
                </p>
            </div>
        </div>
    </main>
{% endblock content %}

templates/pages/pizzavegan-signup.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
{% include 'partials/_alerts.html' %}
<div class="homepage-banner mt-5">
    <div class="homepage-banner__textblock">
        <h2 class="display-4">Welcome!</h2>
        <p>
            Vegan pizza has never been more popular than it is now with 25% of customers looking for more vegan options
            in pizza, but only 25% of pizzerias are offering it. PMQ Pizza Magazine is building a website community and
            national campaign to bring more attention and consumers closer to vegan pizza very soon!
        </p>
        <hr>
        <p class="lead">Are you a...</p>
        <button type="button" class="homepage-banner__button" data-toggle="modal" data-target="#emailSignup">
            Vegan That Loves Pizza
        </button>
        <a href="{% url 'pages:tap-the-table' %}" class="homepage-banner__button">Pizzeria Owner</a>
    </div>
</div>

<div class="modal fade" id="emailSignup" tabindex="-1" aria-labelledby="emailSignupLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <img src="{% static 'images/pizzavegan-color-small.png' %}" alt="PizzaVegan Coming Soon">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-5">
                <p>
                    <strong>Are you vegan and obsessed with pizza?</strong> This will soon be the place for
                    you! Visit us on our opening day, World Vegan Day, November 1!
                </p>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success btn-block">Sign Up</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/pages/tap-the-table.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %} | Register{% endblock title %}

{% block content %}
<div class="container-fluid my-5 py-4 px-4">
    <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-5 mb-4 pr-md-5">
            <img src="{% static 'images/pizzavegan-pin.jpg' %}" alt="PizzaVegan Pin" class="img-fluid mb-4">
            <h2 class="primary-text">Join PMQ's Second National Independent Pizzeria Promotion</h2>
            <p class="lead">
                Drive vegan consumers closer to your vegan pizza through this national vegan pizza promotion
            </p>
            <hr>
            <p>
                <em>PMQ Pizza Magazine</em> is launching PizzaVegan.com, a website community designed to bring more
                attention to&mdash;and consumers closer to&mdash;vegan pizza through exclusive editorial content, a
                product guide, recipes, a directory of independent pizzerias offering vegan pizza, and a kickoff
                promotion during the month of November that begins on World Vegan Day, November 1! Through
                PizzaVegan.com, vegan consumers will have an unprecedented opportunity to find vegan versions of
                Americans' favorite food: pizza.
            </p>
            <h5 class="primary-text">Why Now?</h5>
            <p>Vegan pizza has never been more popular than it is now. Here's a look at the numbers:</p>
            <ul>
                <li>
                    60% of Americans have started to eat a more plant-based diet since the beginning of the pandemic,
                    according to a recent poll of 2,000 adults by OnePoll. Respondents cited health as the No. 1 reason
                    for this change, but they also cited a desire to consume less animal products and lead a more
                    sustainable lifestyle. The same poll revealed that 39% of people ages 18 to 25, and 23% of people
                    ages 26 to 41, already exclude animal products from their diets.
                </li>
                <li>
                    ADM reports that 44% of U.S. consumers identify as flexitarians--those who eat a mostly vegetarian
                    diet, with occasional servings of meat.
                </li>
                <li>
                    The average American eats four meat-free meals per week, and 50% of Americans are trying to
                    incorporate more plant-based meals in their daily lives.
                </li>
                <li>
                    25% of customers are looking for vegan pizza options, but only 25% of pizzerias are offering them.
                </li>
                <li>
                    In 2019, plant-based food sales had increased by 31% over the last two years, according to the
                    Plant Based Foods Association.
                </li>
                <li>
                    Plant-based options are the fastest growing section on pizza menus today, notes trends expert
                    Daniel Levine of the Avant-Guide Institute in New York City.
                </li>
            </ul>
            <h5 class="primary-text">How It Works</h5>
            <p>As a participating pizzeria:</p>
            <ul>
                <li>
                    Provide a link to your online ordering (through the Facebook-based service Tap The Table or your
                    own ordering link), an image, and a description of your vegan pizza offering.
                </li>
                <li>
                    Display point-of-sale elements, such as a window cling, box topper, table tent, door hanger and
                    social media graphics, from November 1 to December 1, 2020. These materials are provided by PMQ
                    Pizza Magazine upon registration.
                </li>
                <li>
                    Maintain the inventory needed for your vegan pizza throughout the month of November!
                </li>
            </ul>
            <p>PMQ will:</p>
            <ul>
                <li>Provide a promotional artwork kit that can be customized with your pizzeria's brand.</li>
                <li>List your pizzeria in the PizzaVegan.com directory.</li>
            </ul>
        </div>
        <div class="col-12 col-md-10 col-lg-5">
            {% include 'partials/_alerts.html' %}
            <p>
                <strong>If you have a Facebook page</strong> and would like to sign up through Facebook Messenger,
                click the button below!
            </p>
            <a href="https://m.me/PMQPizzaMag?ref=Sign-Up" class="btn btn-outline-success btn-block">
                Click Here to Sign Up
            </a>
            <hr class="my-4">
            <p class="text-muted">
                <strong>If you do not have Facebook available right now,</strong> just fill in the form below.
            </p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <p class="text-small text-muted">
                    In order to participate, you must be a subscriber to PMQ Pizza Magazine. If you are not,
                    please <a href="https://www.pmq.com/Subscribe-PMQ/" class="primary-link">click here</a> to fill
                    out the subscription form.
                </p>
                <button type="submit" class="btn btn-outline-success btn-block">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}