pages/urls.py
from django.urls import path

from .views import homepage_view, TapTheTableSignupView, AboutView, MeetEditorView, ContactUsView, \
    pizzavegan_signup_view

app_name = 'pages'
urlpatterns = [
    path('', homepage_view, name='home'),
    path('register/', TapTheTableSignupView.as_view(), name='tap-the-table'),
    path('about/', AboutView.as_view(), name='about'),
    path('meet-the-editor/', MeetEditorView.as_view(), name='meet-the-editor'),
    path('contact/', ContactUsView.as_view(), name='contact_us'),
    path('pizzavegan-signup/', pizzavegan_signup_view, name='pizzavegan-signup'),
]

pizzavegan_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('articles/', include('articles.urls')),
    path('pizzerias/', include('pizzerias.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzerias/urls.py
from django.urls import path

from .views import PizzeriaList, PizzeriaDetail

app_name = 'pizzerias'
urlpatterns = [
    path('', PizzeriaList.as_view(), name='pizzeria_list'),
    path('<int:pk>/', PizzeriaDetail.as_view(), name='pizzeria_detail'),
]

pizzerias/models.py
from django.db import models

# Create your models here.

pizzerias/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.conf import settings

from contacts.models import TapTheTableResponse


class PizzeriaList(ListView):

    model = TapTheTableResponse
    template_name = 'pizzerias/pizzeria_list.html'
    queryset = TapTheTableResponse.objects.filter(is_approved=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['maps_api_key'] = settings.MAPS_API_KEY
        return context


class PizzeriaDetail(DetailView):

    model = TapTheTableResponse
    template_name = 'pizzerias/pizzeria_detail.html'
    context_object_name = 'pizzeria'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['maps_api_key'] = settings.MAPS_API_KEY
        return context

templates/pizzerias/pizzeria_detail.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}
    <main class="container-fluid my-5 px-5">
        <div class="row justify-content-center">
            <article class="col-10 col-md-7 col-lg-5">
                {% if pizzeria.pizza_photo %}
                    <div class="article-header-image mb-4 shadow">
                        <img src="{{ pizzeria.pizza_photo.url }}" class="rounded" />
                    </div>
                {% endif %}
                <div class="article-title mb-4 border-bottom">
                    <h2 class="text-success display-4 font-weight-bold">{{ pizzeria.restaurant_name }}</h2>
                    <p class="lead h5">{{ pizzeria.vegan_pizza_type }}</p>
                </div>
                <div class="article-body">
                    <div class="my-3">
                        <p>{{ pizzeria.menu_description }}</p>
                        {% if pizzeria.facebook_page %}
                        <p>
                            Find {{ pizzeria.restaurant_name }} <a href="#" class="text-success">on Facebook!</a>
                        </p>
                        {% endif %}
                        {% if pizzeria.online_ordering_link %}
                        <p>
                            <a href="#" class="text-success">Order a pizza</a> from {{ pizzeria.restaurant_name }}!
                        </p>
                        {% endif %}
                    </div>
                </div>
                <div id="pizzeria-map"></div>
            </article>
        </div>
    </main>
{% endblock content %}

{% block extrascripts %}
<script>
    function initMap() {
        const pizzeriaLatitude = {{ pizzeria.latitude }};
        const pizzeriaLongitude = {{ pizzeria.longitude }};
        const pizzeriaName = "{{ pizzeria.restaurant_name }}";

        const listingPosition = { lat: pizzeriaLatitude, lng: pizzeriaLongitude };
        const mapCenter = listingPosition;

        const mapDiv = document.getElementById('pizzeria-map');
        const mapOptions = {
            zoom: 13,
            center: mapCenter
        };
        const map = new google.maps.Map(mapDiv, mapOptions);

        const pizzeriaMarker = new google.maps.Marker({
            position: listingPosition,
            map: map,
            title: pizzeriaName
        });
    }
</script>
<script
    defer
    src="https://maps.googleapis.com/maps/api/js?key={{ maps_api_key }}&callback=initMap">
</script>
{% endblock extrascripts %}

templates/pizzerias/pizzeria_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | Pizzerias{% endblock title %}

{% block content %}
<main class="container-fluid my-4">
    <div class="row">
        <div class="d-none d-lg-block col-lg-5">
            <div id="pizzeria-list-map" class="position-sticky sticky-top sticky-offset"></div>
        </div>
        <div class="col-12 col-lg-7">
            <h1 class="font-italic">Vegan Pizzerias</h1>
            <hr>
            <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3">
                {% for pizzeria in tapthetableresponse_list %}
                    <div
                        class="col-12 col-md-6 col-lg-4 d-flex flex-column mt-3 mb-5 pizzeria-card"
                        data-lat="{{ pizzeria.latitude }}"
                        data-lng="{{ pizzeria.longitude }}"
                        data-title="{{ pizzeria.restaurant_name }}"
                    >
                        {% if pizzeria.pizza_photo %}
                            <img src="{{ pizzeria.pizza_photo.url }}" alt="{{ pizzeria.restaurant_name }}" class="articles-list-image rounded" />
                        {% else %}
                            <img src="{% static 'images/pizzavegan-color.png' %}" alt="{{ pizzeria.restaurant_name }}" class="articles-list-default-image rounded">
                        {% endif %}
                        <h4 class="articles-list-post-title mt-3">
                            <a href="{% url 'pizzerias:pizzeria_detail' pizzeria.id %}" class="text-success">
                                {{ pizzeria.restaurant_name }}
                            </a>
                        </h4>
                        <p>{{ pizzeria.vegan_pizza_type }}</p>
                        <a href="{% url 'pizzerias:pizzeria_detail' pizzeria.id %}" class="btn btn-outline-success btn-block mt-auto">
                            View Page
                        </a>
                    </div>
                {% empty %}
                    <p>Sorry, there are no pizzerias listed at this time.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock content %}

{% block extrascripts %}
<script>
    function initMap() {
        const usCenter = { lat: 39.8283, lng: -98.5795 };
        const mapDiv = document.getElementById("pizzeria-list-map");
        const mapOptions = {
            zoom: 4,
            center: usCenter
        };

        const map = new google.maps.Map(mapDiv, mapOptions);

        const pizzerias = document.querySelectorAll(".pizzeria-card");
        const markerArray = new Array();

        pizzerias.forEach((pizzeria, indx) => {
            const pizzeriaPosition = { lat: parseFloat(pizzeria.dataset.lat), lng: parseFloat(pizzeria.dataset.lng) };
            const title = pizzeria.dataset.title;

            const pizzeriaMarker = new google.maps.Marker({
                position: pizzeriaPosition,
                map: map,
                title: title
            });

            markerArray.push(pizzeriaMarker);
        });

        const clusterImagePath = "https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m";

        const markerClusterer = new MarkerClusterer(map, markerArray, { imagePath: clusterImagePath });
    }
</script>
<script
    defer
    src="https://maps.googleapis.com/maps/api/js?key={{ maps_api_key }}&callback=initMap">
</script>
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
{% endblock extrascripts %}