articles/urls.py
from django.urls import path

from .views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, RecipeListView, \
    RecipeDetailView

app_name = 'articles'
urlpatterns = [
    path('', ArticleListView.as_view(), name='articles_list'),
    path('create-new-article/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('article/<slug:slug>/edit/', ArticleUpdateView.as_view(), name='article_update'),
    path('recipes/', RecipeListView.as_view(), name='recipes_list'),
    path('recipes/<slug:slug>/', RecipeDetailView.as_view(), name='recipe_detail'),
]

pages/urls.py
from django.urls import path

from .views import homepage_view, TapTheTableSignupView, AboutView, MeetEditorView, ContactUsView, \
    pizzavegan_signup_view

app_name = 'pages'
urlpatterns = [
    path('', homepage_view, name='home'),
    path('register/', TapTheTableSignupView.as_view(), name='tap-the-table'),
    path('about/', AboutView.as_view(), name='about'),
    path('meet-the-editor/', MeetEditorView.as_view(), name='meet-the-editor'),
    path('contact/', ContactUsView.as_view(), name='contact_us'),
    path('pizzavegan-signup/', pizzavegan_signup_view, name='pizzavegan-signup'),
]

pizzavegan_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('articles/', include('articles.urls')),
    path('pizzerias/', include('pizzerias.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzerias/urls.py
from django.urls import path

from .views import PizzeriaList, PizzeriaDetail

app_name = 'pizzerias'
urlpatterns = [
    path('', PizzeriaList.as_view(), name='pizzeria_list'),
    path('<int:pk>/', PizzeriaDetail.as_view(), name='pizzeria_detail'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PizzaVegan{% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.20/dist/shoelace/shoelace.css">
    <script type="module" src="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.20/dist/shoelace/shoelace.esm.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block extra_head_tags %}{% endblock extra_head_tags %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom px-5">
        <a class="navbar-brand" href="{% url 'pages:home' %}">
            <img src="{% static 'images/pizzavegan-color-small.png' %}" alt="PizzaVerse Logo" loading="lazy">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ml-3">
                    <a href="{% url 'pages:about' %}" class="nav-item nav-link">Why PizzaVegan?</a>
                </li>
                <li class="nav-item ml-3">
                    <a href="{% url 'pages:meet-the-editor' %}" class="nav-item nav-link">Meet the Editor</a>
                </li>
                <li class="nav-item ml-3">
                    <a href="{% url 'pizzerias:pizzeria_list' %}" class="nav-item nav-link">Find Vegan Pizza</a>
                </li>
                <li class="nav-item ml-3">
                    <a href="{% url 'articles:articles_list' %}" class="nav-item nav-link">Articles</a>
                </li>
                <li class="nav-item ml-3">
                    <a href="{% url 'articles:recipes_list' %}" class="nav-item nav-link">Recipes</a>
                </li>
                <li class="nav-item ml-3">
                    <a href="{% url 'pages:pizzavegan-signup' %}" class="nav-item nav-link">Sign Up</a>
                </li>
                <li class="nav-item ml-3">
                    <a href="{% url 'pages:contact_us' %}" class="nav-item nav-link">Contact Us</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}{% endblock content %}

    <footer class="footer">
        <div class="container">
            <span class="text-muted">
                Copyright &copy; <a href="https://www.pmq.com" class="primary-link">PMQ Pizza Magazine</a>
            </span>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>
    {% block extrascripts %}{% endblock extrascripts %}
</body>
</html>